name: Publish Documentation

on:
  push:
    branches: [main]

jobs:
  build_app:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - name: Install gh-pages
        run: |
          npm install -g gh-pages@3.0.0
      - name: Install Dependencies
        run: |
          cd docs
          npm i
          cd ..
      - name: Build Page
        run: |
          cd docs
          npm run build
          echo "blazor.piral.io" > .vitepress/dist/CNAME
          cd ..
      - name: Deploy App Shell
        run: |
          git remote set-url origin https://git:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
          gh-pages -d ".vitepress/dist/release" -u "github-actions-bot <support+actions@github.com>"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
